Feature/marp 315 open rest editor detail pages from within ai designer
axonivy-market/marketplace pull request #75
Opened 2024-08-01 03:17 UTC by nntthuy-axonivy

2024-08-01 08:23 UTC, nqhoan-axonivy requested changes

2024-08-01 08:23 UTC, nqhoan-axonivy commented on marketplace-service/src/main/java/com/axonivy/market/service/impl/ProductServiceImpl.java
> +      searchCriteria.setLanguage(Language.of(Locale.ENGLISH.toLanguageTag()));
Please use Language.EN.getValue()

2024-08-01 08:23 UTC, nqhoan-axonivy commented on marketplace-service/src/main/java/com/axonivy/market/service/impl/ProductServiceImpl.java
> +        break;
Did you change any logic from 226 to 243? If no, please revert the change for that block 226 to 243

2024-08-01 08:23 UTC, nqhoan-axonivy commented on marketplace-service/src/main/java/com/axonivy/market/service/impl/ProductServiceImpl.java
> +      case MODIFIED, ADDED:
Did you change any logic from 249 to 256? If no, please revert the change for that block 249 to 256

2024-08-01 08:23 UTC, nqhoan-axonivy commented on marketplace-ui/src/app/modules/product/product-card/product-card.component.html
> +      [alt]="
hard to read this line, please revert it to old previous version

2024-08-01 08:23 UTC, nqhoan-axonivy commented on marketplace-ui/src/app/modules/product/product-card/product-card.component.ts
> +  isProductInRestClient = inject(ProductComponent).isRestClient();
Please rename to 'isShowInRESTClientEditor' or 'isRenderInRESTClientEditor'

2024-08-01 08:23 UTC, nqhoan-axonivy commented on marketplace-ui/src/app/modules/product/product.component.ts
> +    isRestDesigner: false,
Please chaneg the 'isRestDesigner' to 'isRESTClientEditor'

2024-08-01 08:23 UTC, nqhoan-axonivy commented on marketplace-ui/src/app/shared/enums/request-param.ts
> +  IS_REST_DESIGNER = 'isRestDesigner'
please rename the 'isRestDesigner' to is 'isRESTClientEditor'

2024-08-01 08:23 UTC, nqhoan-axonivy commented on marketplace-ui/src/app/shared/models/criteria.model.ts
> +  isRestDesigner: boolean;
please rename the 'isRestDesigner' to is 'isRESTClientEditor'

2024-08-02 08:31 UTC, tvtphuc-axonivy requested changes

2024-08-02 08:39 UTC, tvtphuc-axonivy requested changes

2024-08-02 08:39 UTC, tvtphuc-axonivy commented on marketplace-ui/src/app/modules/home/home.component.spec.ts
> +  let activatedRoute: ActivatedRoute;
Please remove this line because you didn't use it

2024-08-06 07:21 UTC, tvtphuc-axonivy approved these changes
LGTM

2024-08-07 03:16 UTC, merged